  version: '3.1'

  services:

    db:
      image: postgres
      restart: always
      ports:
        - "5433:5432"
      environment:
        POSTGRES_PASSWORD: postgres

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080